version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # Add environment variables here
      MONGO_URI: mongodb+srv://password1111:password1111@cluster0.5enhd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      EMAIL_PASS: otptjxhxcewaihpb
      EMAIL_USER: olusogaolamileksy@gmail.com
      JWT_SECRET: secret
      STORAGE_URL: https://sportycredit.fra1.digitaloceanspaces.com
      JWT_KEY: secret
      SALT: 10